services:
  - type: web
    name: kupo-nuts-api
    env: node
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg ca-certificates
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update && apt-get install -y google-chrome-stable
      npm run install-all
    startCommand: node my-react-app/server/server.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: PORT
        value: "10000" 
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true

  - type: static
    name: kupo-nuts-frontend
    buildCommand: cd my-react-app && npm install && npm run build
    publishDir: my-react-app/build
    envVars:
      - key: NODE_ENV
        value: production

