services:
  - type: web
    name: kupo-nuts-backend
    runtime: node
    buildCommand: |
      apt-get update && 
      apt-get install -y chromium ca-certificates fonts-freefont-ttf fonts-liberation libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libglib2.0-0 libnspr4 libnss3 libpango-1.0-0 libwayland-client0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils && 
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true

  - type: static
    name: kupo-nuts-frontend
    buildCommand: cd my-react-app && npm install && npm run build
    publishDir: my-react-app/build
    envVars:
      - key: NODE_ENV
        value: production

