services:
  - type: web
    name: kupo-nuts-backend
    runtime: node
    buildCommand: npm install && cd my-react-app/server && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true

  - type: static
    name: kupo-nuts-frontend
    buildCommand: cd my-react-app && npm install && npm run build
    publishDir: my-react-app/build
    envVars:
      - key: NODE_ENV
        value: production

