services:
  - type: web
    name: kupo-nuts-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
